defaults: &defaults
  GOOGLE_MAPS_API_KEY: 'AIzaSyBoGA2VufIq_scXFZmqotG2l5vpQKXPTdU'
  MIN_RADIUS: 5 # <= kilometeres
  MAX_ZOOM: 20
  MIN_ZOOM: 12
development:
  <<: *defaults


test:
  <<: *defaults

production:
  <<: *defaults
