# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eab5dc8061eccd32ab2c32eddf02c390f0123c67eb8aa2e0bdd0493b116a096714e7e19571b27b4e61f5adbaee2b8f8d4133fa13083c1e7def21649e243f76c0

test:
  secret_key_base: d64c49cc5bcc3d6fd8345605f8ccefcf05ec1e1a3b13e2d1e11c3b36265ccbbe9eb293f11d815173654aa3bdc11264fe004c45c0c2005229e2dc8f17f1e98c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
